In [3]:
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

In [4]:
def get_mfccs_mean_vector(mfccs):
  mfccs_mean = []
  for mfcc_feature in mfccs:
      mfccs_mean.append(np.mean(mfcc_feature))
  mfccs_mean = np.array(mfccs_mean)
  return mfccs_mean

In [14]:
training = False
preprocessed = True
normalized = False

In [15]:
if not preprocessed:
    if training and normalized:
        segmented_dataset_path = './2-wav_training/'
        dest_dataset_path = '3-old_mfccs_revisited' + '/normalized/training/'

    elif not training and normalized:
        segmented_dataset_path = './2-wav_testing/'
        dest_dataset_path = '3-old_mfccs_revisited' + '/normalized/testing/'

    elif training and not normalized:
        segmented_dataset_path = './2-wav_training_unnormalized/'
        dest_dataset_path = '3-old_mfccs_revisited' + '/unnormalized/training/'
    elif not training and not normalized:
        segmented_dataset_path = './2-wav_testing_unnormalized/'
        dest_dataset_path = '3-old_mfccs_revisited' + '/unnormalized/testing/'
else:
    if training:
        segmented_dataset_path = './3-wav_training_noise_preprocessed/'
        dest_dataset_path = '3-old_mfccs_revisited' + '/preprocessed/training/'
    else:
        segmented_dataset_path = './3-wav_testing_noise_preprocessed/'
        dest_dataset_path = '3-old_mfccs_revisited' + '/preprocessed/testing/'

directory_names = os.listdir(segmented_dataset_path)
directory_names

['Sherif', 'A', 'O', 'L', 'Y', 'S', 'Reem', 'Renad']

In [16]:
if not os.path.exists(dest_dataset_path):
    os.makedirs(dest_dataset_path)
    print(f"Directory '{dest_dataset_path}' created successfully.")
else:
    print(f"Directory '{dest_dataset_path}' already exists.")

Directory '3-old_mfccs_revisited/preprocessed/testing/' created successfully.


In [17]:
for i in range(len(directory_names)):
  directory_name = directory_names[i] # to change for each directory in the dataset

  src_directory_path = f'{segmented_dataset_path}{directory_name}/'
  dest_directory_path = f'{dest_dataset_path}{directory_name}/'

  google_drive = False
  if google_drive:
      src_directory_path = '/content/drive/MyDrive/thesis_models/' + src_directory_path
      dest_dataset_path = '/content/drive/MyDrive/thesis_models/' + dest_dataset_path
      dest_directory_path = '/content/drive/MyDrive/thesis_models/' + dest_directory_path
  if not os.path.exists(dest_directory_path):
      os.makedirs(dest_directory_path)
      print(f"Directory '{dest_directory_path}' created successfully.")
  else:
      print(f"Directory '{dest_directory_path}' already exists.")
  directory_path = src_directory_path
  output_path = dest_directory_path
  output_path
  file_names = os.listdir(directory_path)
  file_names
  # # columns = [f'MFCC {i}' for i in range(1, 21)]
  # # columns.append('Speaker')
  # # df = pd.DataFrame(columns=columns)
  # vectors = []
  # i = 1
  # for file_name in file_names:
  #   if file_name.split('.')[-1] != "m4a":
  #     continue
  #   file_path = directory_path + file_name
  #   signal, sr = librosa.load(file_path, duration=3)
  #   mfccs = librosa.feature.mfcc(y=signal, n_mfcc=20, sr=sr)
  #   # mfcc_vector = get_mfccs_mean_vector(mfccs)
  #   # mfcc_vector = np.append(mfcc_vector, speaker)
  #   mfcc_vector = mfccs
  #   vectors.append(mfcc_vector)
  #   i += 1

  # librosa.display.specshow(vectors[9], sr=sr)

  # columns = [f'MFCC {i}' for i in range(1, 21)]
  # columns.append('Speaker')
  # df = pd.DataFrame(columns=columns)
  speaker = directory_name
  i = 0
  for file_name in file_names:
    i += 1
    if file_name.split('.')[-1] != "wav":
      continue
    file_path = directory_path + file_name
    signal, sr = librosa.load(file_path, duration=5)
    mfccs = librosa.feature.mfcc(y=signal, n_mfcc=22, sr=sr)
    # mfcc_vector = get_mfccs_mean_vector(mfccs)
    # mfcc_vector = np.append(mfcc_vector, speaker)
    mfcc_vector = mfccs
    df = pd.DataFrame(mfcc_vector)
    df.to_csv(f'{output_path}{speaker}_{i}.csv', index=False)
  df = pd.read_csv(f'{output_path}{speaker}_{i}.csv')
df

Directory '3-old_mfccs_revisited/preprocessed/testing/Sherif/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/A/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/O/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/L/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/Y/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/S/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/Reem/' created successfully.
Directory '3-old_mfccs_revisited/preprocessed/testing/Renad/' created successfully.


0           1           2           3           4           5  \
0  -585.962800 -562.138100 -563.261700 -577.955440 -587.647100 -602.067500   
1    19.033325   -9.480791  -38.449380  -61.776863  -60.180405  -42.689680   
2    46.507896   62.119537   57.447342   41.431824   34.535630   24.726906   
3    23.965515   27.530290   19.452530    2.966575   -1.325888   -1.315569   
4    -4.134559  -18.265705  -26.489513  -33.345848  -28.975079  -20.301952   
5    15.425129   41.542904   54.986797   52.579094   47.718746   34.025760   
6   -34.334923  -53.524185  -57.643856  -57.977990  -51.013412  -36.929300   
7    -8.327235    8.078411   26.287445   38.197800   40.623840   29.969364   
8   -31.628483  -34.746025  -29.706573  -25.283083  -22.615562  -17.182339   
9   -23.869186  -26.663883  -17.974990   -2.193532    4.472020    3.796255   
10  -16.386127  -12.205336   -3.466731    6.730534    7.997142    5.897277   
11  -17.408580  -22.793255  -23.468523  -14.530863  -12.649845  -10.027787   
12   -4.133090   -7.862309   -4.580574    8.299723   11.179970    9.439893   
13   -5.281960   -4.338740   -6.316465   -3.905384   -7.589714   -6.796517   
14    6.217246    0.326920   -2.771613    5.300098    5.833445    5.003300   
15   -6.282021   -9.050435   -8.296444   -5.599406   -7.795626   -5.721541   
16   11.987261   17.525684   15.876492   17.105135   12.513039    8.637966   
17  -12.537056  -24.550950  -23.350960  -18.818974  -16.901924  -11.770187   
18    2.940817   15.427831   20.909424   21.849318   17.526854   12.595981   
19   -6.243233  -16.165468  -17.113450  -14.389695  -12.488616   -9.427256   
20  -16.265965  -13.274126   -4.483715    0.804265    2.507921    2.364847   
21    8.315091   10.335310    8.170924    9.104185    9.286678    6.608340   

             6           7           8           9  ...         206  \
0  -626.339600 -611.146100 -569.727800 -535.477050  ... -505.399380   
1   -13.022606   -8.007019  -21.154402  -35.049656  ...  136.811250   
2     7.562081  -28.137032  -71.169890 -101.001940  ...   62.704666   
3    -0.556811   16.705252   40.247437   58.965992  ...   53.688366   
4    -5.830647    9.763091   25.027330   31.063477  ...   63.034386   
5     9.946924   -9.952173  -19.109121  -18.983418  ...    9.498951   
6   -11.096566    3.945166    1.373490   -5.882264  ...  -62.841827   
7     9.542120   -6.852665  -15.558775  -20.443916  ...  -60.935333   
8    -6.222688   -3.543546    1.803018   11.645988  ...   -7.008147   
9     2.382482   19.961180   33.876380   31.882630  ...    7.587066   
10    0.811098   -7.566401  -16.240665  -16.095194  ...  -18.785313   
11   -2.635680  -19.542927  -29.178883  -29.917517  ...  -14.162136   
12    3.068511   17.203138   22.646542   18.719126  ...   26.200150   
13   -2.753069    7.667313   12.339207   15.615622  ...   36.627262   
14    2.598264  -15.770900  -13.712596  -11.803902  ...    2.747930   
15   -3.186037    4.735328    0.189277    1.075175  ...  -20.679976   
16    4.361733    4.208187   -2.499460   -7.786168  ...  -10.303455   
17   -5.306092   -8.173281   -0.856839    0.214235  ...   -2.104041   
18    5.057426    8.126092   11.965432   15.247013  ...  -15.323250   
19   -3.129021    2.262719   -2.546384   -5.401182  ...  -23.738865   
20   -0.179821  -12.514548  -12.707257   -7.866244  ...  -11.395979   
21    3.928283    5.579520    2.920184   -2.915076  ...    2.325493   

           207         208         209         210         211         212  \
0  -544.570400 -572.733460 -606.434600 -634.522000 -627.596560 -534.304800   
1   114.415344   85.953610   41.566658    3.492505   12.693789  127.969955   
2    82.916550   72.087140   36.814156    3.426649   10.943968   83.961580   
3    59.699990   51.960995   29.698738    3.318669    8.325138   32.095184   
4    39.099277   29.317923   21.269451    3.171178    5.221852   -8.345051   
5     6.182805    8.124111   12.710657    2.987745    2.063837  -27.534412   
6   -26.838402   -8.304610    5.129404

In [13]:
stop here

SyntaxError: invalid syntax (4067800170.py, line 1)

In [ ]:
mfccs.shape

(22, 216)

In [ ]:
# columns = [f'MFCC {i}' for i in range(1, 21)]
# columns.append('Speaker')
# df = pd.DataFrame(columns=columns)
# for file_name in file_names:
#   if file_name.split('.')[-1] != "m4a":
#     continue
#   file_path = directory_path + file_name
#   signal, sr = librosa.load(file_path, duration=3)
#   mfccs = librosa.feature.mfcc(y=signal, n_mfcc=20, sr=sr)
#   mfcc_vector = get_mfccs_mean_vector(mfccs)
#   mfcc_vector = np.append(mfcc_vector, speaker)
#   df = df.append(pd.Series(mfcc_vector, index=df.columns), ignore_index=True)
# df.to_csv(f'{output_path}{speaker}_3sec.csv', index=False)
# df = pd.read_csv(f'{output_path}{speaker}.csv')
# df

IndentationError: ignored

In [ ]:
directories = ['Sherif', 'Omar', 'Renad', 'Reem', 'Youssef']

In [ ]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Set the path to the directory containing your dataset
dataset_directory = "/content/drive/MyDrive/thesis_models/mini_dataset/"

# Lists to store features and labels
X_list = []
y_list = []

# Iterate through each directory in the dataset
for directory in os.listdir(dataset_directory):
    if directory not in directories:
      continue
    if os.path.isdir(os.path.join(dataset_directory, directory)):
        # Get the path to the Excel file in the current directory
        excel_file_path = os.path.join(dataset_directory, directory, f"{directory}.csv")

        # Read the Excel file
        df = pd.read_csv(excel_file_path)

        # Assuming the last column is the target/label column
        X = df.iloc[:, :-1].values  # Features
        y = df.iloc[:, -1].values   # Labels

        # Append the features and labels to the lists
        X_list.append(X)
        y_list.append(y)

# Concatenate the lists to create the final feature and label arrays
X = np.concatenate(X_list, axis=0)
y = np.concatenate(y_list, axis=0)
# print(X)
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7) #, test_size=0.1, random_state=42

# Initialize the SVM model
svm_model = SVC(kernel='linear', C=1.0)

# Train the SVM model
svm_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.5f}")


Accuracy: 0.86667


In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# Set the path to the directory containing your dataset
dataset_directory = "/content/drive/MyDrive/thesis_models/mini_dataset/"

# Lists to store features and labels
X_list = []
y_list = []

# Iterate through each directory in the dataset
for directory in os.listdir(dataset_directory):
    if directory not in directories:
      continue
    if os.path.isdir(os.path.join(dataset_directory, directory)):
        # Get the path to the Excel file in the current directory
        excel_file_path = os.path.join(dataset_directory, directory, f"{directory}.csv")

        # Read the Excel file
        df = pd.read_csv(excel_file_path)

        # Assuming the last column is the target/label column
        X = df.iloc[:, :-1].values  # Features
        y = df.iloc[:, -1].values   # Labels

        # Append the features and labels to the lists
        X_list.append(X)
        y_list.append(y)

# Concatenate the lists to create the final feature and label arrays
X = np.concatenate(X_list, axis=0)

# Use LabelEncoder to convert string labels to integers
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(np.concatenate(y_list, axis=0))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7) #, test_size=0.2, random_state=42

# Initialize the XGBoost model
xgb_model = XGBClassifier()

# Train the XGBoost model
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xgb_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.5f}")


Accuracy: 0.86667


In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# Set the path to the directory containing your dataset
dataset_directory = "/content/drive/MyDrive/thesis_models/mini_dataset/"

# Lists to store features and labels
X_list = []
y_list = []

# Dictionary to store the mapping from numerical labels to class names
class_mapping = {}

# Iterate through each directory in the dataset
for directory in os.listdir(dataset_directory):
    if directory not in directories:
        continue
    if os.path.isdir(os.path.join(dataset_directory, directory)):
        # Get the path to the Excel file in the current directory
        excel_file_path = os.path.join(dataset_directory, directory, f"{directory}.csv")

        # Read the Excel file
        df = pd.read_csv(excel_file_path)

        # Assuming the last column is the target/label column
        X = df.iloc[:, :-1].values  # Features
        y = df.iloc[:, -1].values   # Labels

        # Append the features and labels to the lists
        X_list.append(X)
        y_list.append(y)

        # Update the class mapping without using LabelEncoder
        class_mapping.update({label: class_name for label, class_name in zip(y, y)})

# Concatenate the lists to create the final feature and label arrays
X = np.concatenate(X_list, axis=0)
y_all = np.concatenate(y_list, axis=0)

# Use LabelEncoder to convert string labels to integers for training
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_all)

# Split the data into training and testing sets
X_train, X_test, y_train_encoded, y_test_encoded = train_test_split(X, y_encoded, train_size=0.7)

# Initialize the XGBoost model
xgb_model = XGBClassifier()

# Train the XGBoost model
xgb_model.fit(X_train, y_train_encoded)

# Make predictions on the test set
y_pred_encoded = xgb_model.predict(X_test)

# Map the predicted numerical labels back to class names using the class_mapping dictionary
predicted_class_names = [class_mapping[label] for label in label_encoder.inverse_transform(y_pred_encoded)]

# Calculate accuracy
accuracy = accuracy_score(label_encoder.inverse_transform(y_test_encoded), label_encoder.inverse_transform(y_pred_encoded))
print(f"Accuracy: {accuracy:.5f}")

# Display the predicted class names
print("Predicted Class Names:", predicted_class_names)


Accuracy: 0.86667
Predicted Class Names: ['Sherif', 'Renad', 'Reem', 'Renad', 'Renad', 'Youssef', 'Reem', 'Sherif', 'Omar', 'Renad', 'Renad', 'Omar', 'Youssef', 'Sherif', 'Sherif']


In [ ]:
for key, value in class_mapping.items():
  print(key, value)

Sherif Sherif
Youssef Youssef
Omar Omar
Renad Renad
Reem Reem


In [ ]:
y_pred_encoded

array([3, 2, 1, 2, 2, 4, 1, 3, 0, 2, 2, 0, 4, 3, 3])

In [ ]:
y_test_encoded

array([3, 2, 1, 1, 2, 4, 1, 3, 0, 2, 2, 0, 1, 3, 3])

In [ ]:
test_sample = [[-340.78452,136.54994,6.28157,22.479836,5.836398,3.624558,-6.715408,-3.530711,-5.688966,1.43254,-1.8756343,2.1192057,-0.36051726,-4.1750746,-1.2043107,1.572028,-4.466659,-5.4007607,2.8591537,-4.360394]]

In [ ]:
y_pred_sample_encoded = xgb_model.predict(test_sample)
speaker = [class_mapping[label] for label in label_encoder.inverse_transform(y_pred_sample_encoded)]
speaker

['Omar']

In [ ]:
def simple_cnn(num_classes):
  model = tf.keras.models.Sequential([
      tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(X.shape[1], 1)),
      tf.keras.layers.MaxPooling2D(2, 2),
      tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
      tf.keras.layers.MaxPooling2D(2, 2),
      tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
      tf.keras.layers.MaxPooling2D(2, 2),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dropout(0.5),
      tf.keras.layers.Dense(num_classes, activation='softmax')  # Assuming three classes
  ])
  model.summary()
  return model

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
num_features = 20

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8) #, test_size=0.2, random_state=42

In [ ]:
model = tf.keras.models.Sequential()
model.add(Dense(128, input_dim=num_features, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))
model.add(Dense(5, activation='softmax'))  # softmax for 5 classes

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Convert labels to one-hot encoding
y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes=5)
y_test_one_hot = tf.keras.utils.to_categorical(y_test, num_classes=5)


# Train the model
model.fit(X_train, y_train_one_hot, epochs=1000, batch_size=64) #, validation_split=0.2

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test_one_hot)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

ValueError: ignored

In [ ]:
y_train

array(['Renad', 'Reem', 'Omar', 'Renad', 'Omar', 'Reem', 'Omar', 'Sherif',
       'Sherif', 'Sherif', 'Omar', 'Renad', 'Reem', 'Omar', 'Renad',
       'Sherif', 'Reem', 'Omar', 'Omar', 'Reem', 'Renad', 'Youssef',
       'Sherif', 'Reem', 'Youssef', 'Youssef', 'Renad', 'Renad', 'Reem',
       'Youssef', 'Youssef', 'Youssef', 'Omar', 'Omar', 'Omar', 'Sherif',
       'Youssef', 'Reem', 'Sherif', 'Sherif'], dtype=object)

In [ ]:
y_test

array([0, 0, 3, 4, 0, 0, 2, 1, 1, 1])

In [ ]:
preds = model.predict(X_test)
predicted_classes = np.argmax(preds, axis=1)
predicted_classes

1/1 [==============================] - 0s 138ms/step


array([0, 0, 3, 4, 1, 0, 2, 1, 1, 1])

In [ ]:
map_names = {
    1: 'Sherif',
    2: 'Reem',
    3: 'Renad',
    4: 'Omar',
    5: 'Youssef'
}
predicted_class = map_names[1]
predicted_class

'Sherif'

In [ ]:
xgb_model = XGBClassifier()

# Train the XGBoost model
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xgb_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.5f}")

Accuracy: 0.80000
